# Generated by Django 4.0.3 on 2022-04-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
